### PR TITLE
added grafana dashboard and screenshot

### PR DESCRIPTION
**Pull request by christianknell**

### CODE REVIEW

**Comment by christianknell** [comment]
fixes https://github.com/mrueg/netcupscp-exporter/issues/4

**Comment by mrueg** [comment]
Thanks! Do you mind including it in the README.md as well?

**Comment by christianknell** [comment]
Has been added. Additionally I added Tags to the dashboard and fixed a templating bug.

**Comment by mrueg** [comment]
Thanks!

**Pull request merged**
